artifacts_root: artifacts

data_ingestion:
      root_dir: artifacts/data_ingestion
      source_url: https://github.com/DsThakurRawat/DsThakurRawat-AIML-IN-PRODUCTION-1-Texti/raw/refs/heads/main/summarizer-data.zip
      local_data_file: artifacts/data_ingestion/summarizer-data.zip
      unzip_dir: artifacts/data_ingestion
      
data_validation:
      root_dir: artifacts/data_validation
      STATUS_FILE: artifacts/data_validation/status.yaml
      ALL_REQUIRED_FILES: ["samsum-train.csv", "samsum-test.csv", "samsum-validation.csv"]
data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/samsum_dataset
  tokenizer_name: google/pegasus-cnn_dailymail